pika:
  version: v3.5.5
image:
  pika:
    registry: docker.io
    repository: pikadb/pika
    tag: v3.5.5
    pullPolicy: IfNotPresent
  redis:
    registry: docker.io
    repository: redis
    tag: 7.2
    pullPolicy: IfNotPresent
  pikaExporter:
    registry: docker.io
    repository: pika-exporter
    tag: v3.5.5
    pullPolicy: IfNotPresent
  redisSentinel:
    registry: docker.io
    repository: redis-sentinel
    tag: v7.0.7
    pullPolicy: IfNotPresent
roleProbe:
  pika:
    failureThreshold: 2
    periodSeconds: 1
    timeoutSeconds: 1
nameOverride: ""
fullnameOverride: ""
clusterDomain: ".cluster.local"
