apiVersion: network.hulk.qihoo.net/v1alpha1
kind: LoadBalancer
metadata:
  name: pika-codis-fe-loadbalance
  labels:
    {{- include "pika.labels" . | nindent 4 }}
    component: pika-codis-fe-loadbalance
spec:
  provider:
    type: '0'
    version: '4'
  selector:
    app.kubernetes.io/component: codis-fe
    apps.kubeblocks.io/component-name: codis-fe
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      scheduling: wrr
      probe:
        tcpSocket: {}