apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentVersion
metadata:
  name: redis-sentinel-pika
  labels:
    {{- include "pika.labels" . | nindent 4 }}
spec:
  compatibilityRules:
    - compDefs:
        - redis-sentinel
      releases:
        - {{ .Chart.AppVersion }}
  releases:
    - name: {{ .Chart.AppVersion }}
      changes:
      serviceVersion: {{ .Chart.AppVersion }}
      images:
        redis-sentinel: {{ include "redisSentinel.image" . }}
