apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentDefinition
metadata:
  name: pika-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pika.labels" . | nindent 4 }}
spec:
  provider: pika
  description: A pika exporter component definition
  serviceKind: pika-exporter
  serviceVersion: {{ .Chart.AppVersion }}
  services:
    - name: exporter
      spec:
        ports:
          - name: exporter
            port: 9121
            targetPort: exporter
  updateStrategy: Serial
  configs:
    - name: pika-config
      templateRef: pika-conf-template
      namespace: {{ .Release.Namespace }}
      volumeName: config
  runtime:
    initContainers:
      - name: wait-pika
        image: busybox:1.28
        command:
          - 'sh'
          - '-c'
          - "until nc -z pika-master 9221; do echo waiting for pika master; sleep 2; done;"
    containers:
      - name: pika-exporter
        image: {{ include "pikaExporter.image" . }}
        imagePullPolicy: {{ include "pikaExporter.imagePullPolicy" . }}
        ports:
          - name: exporter
            containerPort: 9121
        volumeMounts:
          - name: config
            mountPath: /etc/pika
        env:
          - name: PIKA_ADDR
            value: "pika-master:9221"
        command:
          - "/pika/bin/pika_exporter"
        args:
          - "-config"
          - "/etc/pika/info.toml"
          - "-pika.addr"
          - "$(PIKA_ADDR)"
